version: '3'

networks:
  app-network:


services:
  app:
    image: node:18-alpine
    build:
      context: .
      dockerfile: ./Dockerfile
    ports: 
      - "3000:3000"
    networks:
      - app-network
    restart:
      unless-stopped
    expose:
      - "3000"